### ISSUE TITLE
Implement features to back up the database

### ISSUE THREAD

**Issue by TaiSakuma** [simonsobs/acondbs#12]
#### Implement features to back up the database

**The initial backup plan:**  export the DB contents to CSV files and push them to GitHub.

##### Features to implement
- [x] export the DB contents to CSV files https://github.com/simonsobs/acondbs/issues/15
- [x] manage CSV files with git https://github.com/simonsobs/acondbs/issues/16
- [x] push CSV files to GitHub https://github.com/simonsobs/acondbs/issues/17
- [x] trigger the backup https://github.com/simonsobs/acondbs/issues/18
    - the backup needs to be taken whenever the DB contents change
    - the backup should not happen too frequently so as not to stretch the server too much

**Comment by TaiSakuma** [comment]
complete
